/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.chatbotc;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import modelo.chatbotm;

/**
 *
 * @author LAB-USR-LNORTE
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        chatbotm chatbot = new chatbotm();
        mostrarBienvenida();
        agregarListeners();
        lblInstagramMouseClicked.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnviar = new javax.swing.JButton();
        txtCampoPre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txpConver = new javax.swing.JTextPane();
        lblInstagramMouseClicked = new javax.swing.JLabel();
        lblFacebook = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEnviar.setText("Enviar");

        txtCampoPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoPreActionPerformed(evt);
            }
        });

        txpConver.setEditable(false);
        jScrollPane2.setViewportView(txpConver);

        lblInstagramMouseClicked.setText("Instagram");

        lblFacebook.setText("Facebook");

        jLabel2.setText("Whatsapp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCampoPre)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInstagramMouseClicked)
                            .addComponent(jLabel2))))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblInstagramMouseClicked)
                        .addGap(33, 33, 33)
                        .addComponent(lblFacebook)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCampoPre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCampoPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoPreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoPreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            vista ventana = new vista();
            ventana.setVisible(true);
            chatbotm Modelo = new chatbotm();
            chatbotc Controlador = new chatbotc(Modelo, ventana);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFacebook;
    private javax.swing.JLabel lblInstagramMouseClicked;
    private javax.swing.JTextPane txpConver;
    private javax.swing.JTextField txtCampoPre;
    // End of variables declaration//GEN-END:variables

    // Método para agregar un ActionListener al botón enviar
    public void enviarPregunta(ActionListener listenEnviar) {
        btnEnviar.addActionListener(listenEnviar);
    }

    // Métodos para obtener y mostrar la pregunta/respuesta
    public String getPregunta() {
        return txtCampoPre.getText();
    }

    public void mostrarRespuesta(String respuesta) {
        textoConver("Glowy: " + respuesta + "\n", Color.RED); // Texto del chatbot en rojo
    }

    public void mostrarRespuestaUsuario(String entrada) {
        textoConver("Usuario: " + entrada + "\n", Color.BLUE); // Texto del usuario en azul
    }

    private void textoConver(String text, Color color) {
        StyledDocument doc = txpConver.getStyledDocument();
        SimpleAttributeSet atributos = new SimpleAttributeSet();
        StyleConstants.setForeground(atributos, color);

        try {
            doc.insertString(doc.getLength(), text, atributos);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void limpiarCampoTexto() {
        txtCampoPre.setText("");
    }

    private void mostrarBienvenida() {
        mostrarRespuesta("Bienvenido a K-Beauty!");
    }

    private void abrirEnlace(String url) {
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void agregarListeners() {
        lblInstagramMouseClicked.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                abrirEnlace("https://www.youtube.com/watch?v=w2C6RhQBYlg");
            }
        });

        lblFacebook.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                abrirEnlace("https://www.youtube.com/watch?v=w2C6RhQBYlg"); // URL de Facebook
            }
        });
        lblFacebook.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
;


}
